import { OnModuleInit, OnModuleDestroy } from '@nestjs/common';
type PrismaClientType = {
    [key: string]: any;
    $connect(): Promise<void>;
    $disconnect(): Promise<void>;
    $transaction<T>(fn: (tx: any) => Promise<T>, options?: any): Promise<T>;
    $queryRaw<T = unknown>(query: any, ...values: any[]): Promise<T>;
};
export declare class PrismaService implements OnModuleInit, OnModuleDestroy {
    private readonly logger;
    private isConnected;
    private _client;
    constructor();
    get user(): any;
    get role(): any;
    get workRole(): any;
    get employeeProfile(): any;
    get userRole(): any;
    get refreshSession(): any;
    get loginAttempt(): any;
    get reportingPeriod(): any;
    get periodTransition(): any;
    get sprintPlan(): any;
    get sprintPlanVersion(): any;
    get plannedTask(): any;
    get youTrackIssue(): any;
    get youtrackIssue(): any;
    get workItem(): any;
    get integrationSettings(): any;
    get syncRun(): any;
    get syncLogEntry(): any;
    get managerEvaluation(): any;
    get businessEvaluation(): any;
    get personalReport(): any;
    get personalReportLine(): any;
    get summaryReport(): any;
    get employeeRate(): any;
    get employeeRateHistory(): any;
    get formulaConfiguration(): any;
    get formulaConfigurationVersion(): any;
    get evaluationScale(): any;
    get notificationTemplate(): any;
    get notificationRun(): any;
    get outboxMessage(): any;
    get auditLog(): any;
    get periodSnapshot(): any;
    get planningSettings(): any;
    get smtpConfig(): any;
    get exportJob(): any;
    get timesheet(): any;
    get workRoleAssignment(): any;
    $transaction<T>(fn: (tx: any) => Promise<T>, options?: any): Promise<T>;
    $queryRaw<T = unknown>(query: any, ...values: any[]): Promise<T>;
    get $client(): PrismaClientType;
    onModuleInit(): Promise<void>;
    onModuleDestroy(): Promise<void>;
    private connectWithRetry;
}
export {};
